version: '3.3'

services:
  mysql-app:
    image: mysql:8.0.32
    environment:
      MYSQL_USER: flip_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ./_infrastructure/mysql/datadir/:/var/lib/mysql
      - ./_infrastructure/mysql/init/:/docker-entrypoint-initdb.d/
  flip-app:
    #    image: flip
    build: .
    restart: always
    depends_on:
      - mysql-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-app:3306/flip
      SPRING_DATASOURCE_USERNAME: flip_user
      SPRING_DATASOURCE_PASSWORD: password
#      - MYSQL_ROOT_HOST=%
#      DATABASE_HOST: mysql-app
#      - DATABASE_NAME=flip
#      - DATABASE_USER=flip_user
#      - DATABASE_PASSWORD=password
#      - DATABASE_PORT=3306
    ports:
      - 8000:8000
