CREATE DATABASE flip;
CREATE USER 'flip_user'@'localhost' IDENTIFIED BY 'password';
UPDATE mysql.user SET USER='flip_user' WHERE USER='flip_user';
FLUSH PRIVILEGES;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, REFERENCES ON flip.* TO 'flip_user';
